# Supabase PostgreSQL
spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-2.pooler.supabase.com:6543/postgres?sslmode=require
spring.datasource.username=postgres.hlxpwkbyledjgfoyjzcf
spring.datasource.password=k9jkIMHwzcU9wzw4
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=3m9kP0s8xJqZl9dK8vWc2nR5aFhT1uYq==
jwt.expiration=86400000

# Gemini
gemini.api.key=AIzaSyCGz0FjqxCNhkJODS-PGHBoP3sCN8iESos
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent

# Facebook
facebook.api.url=https://graph.facebook.com/v20.0
# facebook.app.id=1495916475274800
facebook.app.id=26887276514216369
# facebook.app.secret=926d6ce976666a248ca5a124e89e4466
facebook.app.secret=e104c7f8dff56bbff7dd52230ef5a285
facebook.oauth.authorize-url=https://www.facebook.com/v20.0/dialog/oauth
facebook.oauth.token-url=https://graph.facebook.com/v20.0/oauth/access_token
facebook.oauth.redirect-uri=http://localhost:8080/api/auth/facebook/callback
app.frontend.url=http://localhost:5173
# CORS
app.cors.allowed-origins=http://localhost:5173