-- University "Join ID": a short, shareable code a Department or Program enters at creation time to be
-- listed as a sub-organization of that university. It replaces pasting a raw parent organization UUID.
--
-- Every statement is idempotent. The backend runs this file at startup (spring.sql.init, before Hibernate
-- validates the schema), and it can equally be pasted into the Supabase SQL editor. Universities created
-- before this column existed get their Join ID generated by the backend the first time it is needed.

ALTER TABLE organizations ADD COLUMN IF NOT EXISTS join_id varchar(32);

CREATE UNIQUE INDEX IF NOT EXISTS uq_organizations_join_id ON organizations (join_id);
